name: Deploy on TargetServer

on:
  push:
    branches:
      - 'master'

jobs:
  FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.ftp_server }}
          FTP_USERNAME: ${{ secrets.ftp_user }}
          FTP_PASSWORD: ${{ secrets.ftp_pwd }}
          REMOTE_DIR : /htdocs/
          ARGS: --delete --verbose --exclude-glob=.git*/** --exclude-glob=.git**