name: Deploy on TargetServer

on:
  push:
    branches:
      - 'master'

jobs:
  FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          server-dir : /htdocs/
          exclude: .git*
            - .git*/**
            -  **/.git*/**
          log-level: verbose
          dangerous-clean-slate: true
