name: Deploy on TargetServer

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp_server: ${{ secrets.ftp_server }}
        ftp_username: ${{ secrets.ftp_user }}
        ftp_password: ${{ secrets.ftp_pwd }}
        remote_dir: /htdocs/
