name: Deploy on TargetServer

on:
  push:
    branches:
      - 'main'

jobs:
  FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
        - name: checkout web content
          uses: actions/checkout@main

        - name: FTP-Deploy-Action
          uses: SamKirkland/FTP-Deploy-Action@4.3.0
          with:
            server: ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_user }}
            password: ${{ secrets.ftp_pwd }}
            server-dir : /htdocs/
            exclude: |
              .git*
              .git*/**
              **/.git*
              **/.git*/**
              **/node_modules/**
            log-level: standard
            dangerous-clean-slate: true
